= What Mr. Spock would possibly say about modern unit testing: pragmatic and emotional overview
Yaroslav Yermilov <https://github.com/yermilov[icon:github[] @yermilov] https://twitter.com/yermilov17[icon:twitter[] @yermilov17] https://www.facebook.com/yaroslav.yermilov[icon:facebook[] @yaroslav.yermilov]>
2016 May 20
:toc:
:icons: font
:linkattrs:

== Original Talk

This is a textual version of link:http://jeeconf.com/program/what-mr-spock-would-possibly-say-about-modern-unit-testing-pragmatic-and-emotional-overview/[the talk given at JEEConf 2016, window="_blank"].

Slides from the talk:

pass:[<iframe src="http://www.slideshare.net/slideshow/embed_code/key/ehE5vzQ7yu5map" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe>]

== Code Examples

All code examples can be found link:https://github.com/yermilov/spock-talk[at GitHub, window="_blank"].

== About Me

I have 5 year experience working in the Java world starting from Intern in EPAM Systems to Senior Software Engineer today in the same company.
Most of this time I've worked in Big Data area, developing various extensions for Hadoop-family tools. Almost accidentally, 2 years ago I became responsible for automated testing on my project.
Out of work, I'm inspired by Groovy ecosystem and data science.

== Agenda

In this article I will cover following questions:

* What’s about modern unit testing?
* Why try Spock?
* How to start with Spock?
* Advanced and hidden features
* What JUnit/TestNG/Mockito offers instead?
* Why use Spock?
* Why do not use Spock?
* When use Spock?
